# Generated by Django 4.2.7 on 2023-11-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disasterfeedback',
            old_name='date_time_of_alert',
            new_name='date_time_of_feedback',
        ),
    ]
