# Generated by Django 4.2.7 on 2023-11-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_name', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.alertchoices'),
        ),
    ]
