# Generated by Django 4.2.7 on 2023-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alertchoices_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
